  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
    ports:
      - "54320:5432"  

  adminer:
    image: adminer
    restart: always
    ports:
      - 9080:8080
